@description('Name of the Static Web App - must be globally unique across Azure.')
param name string

@description('Azure region. Static Web Apps only deploy to a specific subset of regions (e.g. centralus, westus2, westeurope, eastasia).')
param location string

@description('SKU tier.')
@allowed(['Free', 'Standard'])
param skuTier string = 'Free'

@description('GitHub repository URL this Static Web App deploys from.')
param repositoryUrl string

@description('Branch this Static Web App tracks.')
param branch string

@description('GitHub token used to create the repository connection. Only required the first time this resource is created (Azure uses it once, to register the connection); leave empty on later updates to an existing Static Web App. Secure - supplied at deploy time, never a literal or default.')
@secure()
param repositoryToken string = ''

@description('Tags applied to the Static Web App.')
param tags object = {}

resource staticWebApp 'Microsoft.Web/staticSites@2023-12-01' = {
  name: name
  location: location
  tags: tags
  sku: {
    name: skuTier
    tier: skuTier
  }
  properties: {
    repositoryUrl: repositoryUrl
    branch: branch
    repositoryToken: repositoryToken
    buildProperties: {
      // The actual GitHub Actions workflow
      // (.github/workflows/azure-static-web-apps.yml) was added and is
      // maintained by hand, not generated by this resource - see
      // day-17/README.md. Telling Azure not to manage its own copy
      // avoids two workflow files fighting over the same deployment.
      skipGithubActionWorkflowGeneration: true
    }
  }
}

output defaultHostname string = staticWebApp.properties.defaultHostname
